namespace Eu4Indexer.Core.Database

/// PostgreSQL DDL and dialect. Mirrors the SQLite schema (Schema.fs) table for
/// table and column for column, so the same positional INSERT statements work,
/// but uses Postgres types. Keys are INTEGER (int4) to match the Int32 ids the
/// indexer assigns — this also keeps Npgsql's binary parameter encoding in step
/// once statements auto-prepare. The auto-assigned override/option/ref ids use
/// GENERATED ... AS IDENTITY, and foreign keys are DEFERRABLE (checked at commit)
/// to allow the same bulk-load insert order as SQLite. Secondary indexes and
/// views are portable and reused from Schema. Full-text search is replaced by
/// pg_trgm GIN indexes, which give the same CJK substring matching as the
/// SQLite trigram tokenizer.
module PostgresSchema =

    /// Clean slate for an existing target: drop our tables (CASCADE also removes
    /// the dependent views). Other objects in the database are left untouched.
    let private dropSql =
        """
DROP TABLE IF EXISTS
    meta, sources, source_tags, source_dependencies, source_replace_paths,
    files, parse_errors, file_overrides, symbols, config_types,
    entities, entity_overrides, script_nodes, event_details, event_options,
    mission_details, mission_requirements, focus_details, focus_requirements, decision_details, modifier_values,
    entity_localisation, localisation, loc_overrides, refs
CASCADE;
"""

    let tablesSql (gameId: string) =
        """
CREATE TABLE meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE sources (
    source_id         INTEGER PRIMARY KEY,
    kind              TEXT NOT NULL CHECK (kind IN ('base_game','mod')),
    load_order        INTEGER NOT NULL UNIQUE,
    name              TEXT NOT NULL,
    root_path         TEXT NOT NULL,
    descriptor_path   TEXT,
    mod_version       TEXT,
    supported_version TEXT,
    remote_file_id    TEXT,
    picture           TEXT
);

CREATE TABLE source_tags (
    source_id INTEGER NOT NULL REFERENCES sources(source_id) DEFERRABLE INITIALLY DEFERRED,
    tag       TEXT NOT NULL,
    PRIMARY KEY (source_id, tag)
);

CREATE TABLE source_dependencies (
    source_id  INTEGER NOT NULL REFERENCES sources(source_id) DEFERRABLE INITIALLY DEFERRED,
    dependency TEXT NOT NULL,
    PRIMARY KEY (source_id, dependency)
);

CREATE TABLE source_replace_paths (
    source_id INTEGER NOT NULL REFERENCES sources(source_id) DEFERRABLE INITIALLY DEFERRED,
    path      TEXT NOT NULL,
    PRIMARY KEY (source_id, path)
);

CREATE TABLE files (
    file_id       INTEGER PRIMARY KEY,
    source_id     INTEGER NOT NULL REFERENCES sources(source_id) DEFERRABLE INITIALLY DEFERRED,
    relative_path TEXT NOT NULL,
    folder        TEXT NOT NULL,
    file_name     TEXT NOT NULL,
    content_hash  TEXT NOT NULL,
    byte_size     INTEGER NOT NULL,
    is_effective  INTEGER NOT NULL DEFAULT 1,
    parse_status  TEXT NOT NULL DEFAULT 'ok'
                  CHECK (parse_status IN ('ok','error','skipped')),
    UNIQUE (source_id, relative_path)
);

CREATE TABLE parse_errors (
    file_id INTEGER NOT NULL REFERENCES files(file_id) DEFERRABLE INITIALLY DEFERRED,
    message TEXT NOT NULL,
    line    INTEGER,
    col     INTEGER
);

CREATE TABLE file_overrides (
    override_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind              TEXT NOT NULL CHECK (kind IN ('shadow','replace_path')),
    relative_path     TEXT NOT NULL,
    loser_file_id     INTEGER NOT NULL REFERENCES files(file_id) DEFERRABLE INITIALLY DEFERRED,
    winner_file_id    INTEGER REFERENCES files(file_id) DEFERRABLE INITIALLY DEFERRED,
    winner_source_id  INTEGER NOT NULL REFERENCES sources(source_id) DEFERRABLE INITIALLY DEFERRED,
    loser_source_id   INTEGER NOT NULL REFERENCES sources(source_id) DEFERRABLE INITIALLY DEFERRED,
    identical_content INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE symbols (
    symbol_id INTEGER PRIMARY KEY,
    name      TEXT NOT NULL,
    kind      TEXT NOT NULL CHECK (kind IN ('trigger','effect','modifier')),
    scope     TEXT,
    cwt_file  TEXT NOT NULL,
    UNIQUE (kind, name)
);

CREATE TABLE config_types (
    type_name        TEXT PRIMARY KEY,
    name_field       TEXT,
    paths            TEXT NOT NULL,
    type_per_file    INTEGER NOT NULL DEFAULT 0,
    skip_root_key    TEXT,
    localisation_map TEXT
);

CREATE TABLE entities (
    entity_id    INTEGER PRIMARY KEY,
    entity_type  TEXT NOT NULL,
    entity_key   TEXT NOT NULL,
    file_id      INTEGER NOT NULL REFERENCES files(file_id) DEFERRABLE INITIALLY DEFERRED,
    source_id    INTEGER NOT NULL REFERENCES sources(source_id) DEFERRABLE INITIALLY DEFERRED,
    start_line   INTEGER NOT NULL,
    end_line     INTEGER NOT NULL,
    stmt_index   INTEGER NOT NULL,
    subtypes     TEXT,
    raw_text     TEXT NOT NULL,
    is_effective INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE entity_overrides (
    override_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind              TEXT NOT NULL CHECK (kind IN ('redefinition','file_shadow','replace_path')),
    entity_type       TEXT NOT NULL,
    entity_key        TEXT NOT NULL,
    loser_entity_id   INTEGER NOT NULL REFERENCES entities(entity_id) DEFERRABLE INITIALLY DEFERRED,
    winner_entity_id  INTEGER REFERENCES entities(entity_id) DEFERRABLE INITIALLY DEFERRED,
    winner_source_id  INTEGER REFERENCES sources(source_id) DEFERRABLE INITIALLY DEFERRED,
    loser_source_id   INTEGER NOT NULL REFERENCES sources(source_id) DEFERRABLE INITIALLY DEFERRED,
    identical_content INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE script_nodes (
    node_id    INTEGER PRIMARY KEY,
    entity_id  INTEGER NOT NULL REFERENCES entities(entity_id) DEFERRABLE INITIALLY DEFERRED,
    parent_id  INTEGER REFERENCES script_nodes(node_id) DEFERRABLE INITIALLY DEFERRED,
    depth      INTEGER NOT NULL,
    sort_order INTEGER NOT NULL,
    node_kind  TEXT NOT NULL CHECK (node_kind IN ('clause','leaf','value')),
    context    TEXT NOT NULL CHECK (context IN ('trigger','effect','mtth','ai_chance','metadata')),
    key        TEXT,
    "operator" TEXT,
    value      TEXT,
    value_kind TEXT CHECK (value_kind IN ('int','float','bool','date','string')),
    symbol_id  INTEGER REFERENCES symbols(symbol_id) DEFERRABLE INITIALLY DEFERRED,
    line       INTEGER NOT NULL
);

CREATE TABLE event_details (
    entity_id         INTEGER PRIMARY KEY REFERENCES entities(entity_id) DEFERRABLE INITIALLY DEFERRED,
    namespace         TEXT NOT NULL,
    event_kind        TEXT NOT NULL CHECK (event_kind IN ('country','province','news','state','unit_leader','operative_leader')),
    title_key         TEXT,
    desc_key          TEXT,
    picture           TEXT,
    is_triggered_only INTEGER NOT NULL DEFAULT 0,
    hidden            INTEGER NOT NULL DEFAULT 0,
    fire_only_once    INTEGER NOT NULL DEFAULT 0,
    major             INTEGER NOT NULL DEFAULT 0,
    has_mtth          INTEGER NOT NULL DEFAULT 0,
    option_count      INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE event_options (
    option_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id  INTEGER NOT NULL REFERENCES entities(entity_id) DEFERRABLE INITIALLY DEFERRED,
    option_idx INTEGER NOT NULL,
    name_key   TEXT,
    node_id    INTEGER NOT NULL REFERENCES script_nodes(node_id) DEFERRABLE INITIALLY DEFERRED,
    UNIQUE (entity_id, option_idx)
);

CREATE TABLE mission_details (
    entity_id     INTEGER PRIMARY KEY REFERENCES entities(entity_id) DEFERRABLE INITIALLY DEFERRED,
    series_key    TEXT NOT NULL,
    slot          INTEGER,
    is_generic    INTEGER NOT NULL DEFAULT 0,
    ai            INTEGER NOT NULL DEFAULT 1,
    icon          TEXT,
    position      INTEGER,
    has_highlight INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE mission_requirements (
    entity_id        INTEGER NOT NULL REFERENCES entities(entity_id) DEFERRABLE INITIALLY DEFERRED,
    required_mission TEXT NOT NULL,
    PRIMARY KEY (entity_id, required_mission)
);


CREATE TABLE focus_details (
    entity_id            INTEGER PRIMARY KEY REFERENCES entities(entity_id) DEFERRABLE INITIALLY DEFERRED,
    tree_id              TEXT NOT NULL,
    icon                 TEXT,
    x                    INTEGER,
    y                    INTEGER,
    relative_position_id TEXT
);

CREATE TABLE focus_requirements (
    entity_id      INTEGER NOT NULL REFERENCES entities(entity_id) DEFERRABLE INITIALLY DEFERRED,
    required_focus TEXT NOT NULL,
    PRIMARY KEY (entity_id, required_focus)
);
CREATE TABLE decision_details (
    entity_id     INTEGER PRIMARY KEY REFERENCES entities(entity_id) DEFERRABLE INITIALLY DEFERRED,
    major         INTEGER NOT NULL DEFAULT 0,
    ai_importance DOUBLE PRECISION
);

CREATE TABLE modifier_values (
    entity_id    INTEGER NOT NULL REFERENCES entities(entity_id) DEFERRABLE INITIALLY DEFERRED,
    modifier_key TEXT NOT NULL,
    value        TEXT NOT NULL,
    symbol_id    INTEGER REFERENCES symbols(symbol_id) DEFERRABLE INITIALLY DEFERRED,
    PRIMARY KEY (entity_id, modifier_key)
);

CREATE TABLE entity_localisation (
    entity_id INTEGER NOT NULL REFERENCES entities(entity_id) DEFERRABLE INITIALLY DEFERRED,
    role      TEXT NOT NULL,
    loc_key   TEXT NOT NULL,
    PRIMARY KEY (entity_id, role)
);

CREATE TABLE localisation (
    loc_id       INTEGER PRIMARY KEY,
    loc_key      TEXT NOT NULL,
    language     TEXT NOT NULL,
    value        TEXT NOT NULL,
    value_plain  TEXT NOT NULL DEFAULT '',
    version_num  INTEGER,
    file_id      INTEGER NOT NULL REFERENCES files(file_id) DEFERRABLE INITIALLY DEFERRED,
    source_id    INTEGER NOT NULL REFERENCES sources(source_id) DEFERRABLE INITIALLY DEFERRED,
    is_replace   INTEGER NOT NULL DEFAULT 0,
    is_effective INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE loc_overrides (
    override_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loc_key           TEXT NOT NULL,
    language          TEXT NOT NULL,
    kind              TEXT NOT NULL CHECK (kind IN
        ('later_source','replace_dir','same_source_duplicate','file_shadow','replace_path')),
    loser_loc_id      INTEGER NOT NULL REFERENCES localisation(loc_id) DEFERRABLE INITIALLY DEFERRED,
    winner_loc_id     INTEGER REFERENCES localisation(loc_id) DEFERRABLE INITIALLY DEFERRED,
    winner_source_id  INTEGER REFERENCES sources(source_id) DEFERRABLE INITIALLY DEFERRED,
    loser_source_id   INTEGER NOT NULL REFERENCES sources(source_id) DEFERRABLE INITIALLY DEFERRED,
    identical_content INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE refs (
    ref_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_entity_id INTEGER NOT NULL REFERENCES entities(entity_id) DEFERRABLE INITIALLY DEFERRED,
    from_context   TEXT NOT NULL,
    ref_kind       TEXT NOT NULL,
    target_type    TEXT NOT NULL,
    target_key     TEXT NOT NULL,
    node_id        INTEGER NOT NULL REFERENCES script_nodes(node_id) DEFERRABLE INITIALLY DEFERRED,
    option_node_id INTEGER REFERENCES script_nodes(node_id) DEFERRABLE INITIALLY DEFERRED,
    negated        INTEGER NOT NULL DEFAULT 0
);
"""

    /// pg_trgm GIN indexes mirror the SQLite trigram FTS: substring/CJK matching
    /// over the markup-stripped localisation text and the raw entity script.
    let searchSql =
        """
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX idx_loc_value_trgm  ON localisation USING gin (value_plain gin_trgm_ops);
CREATE INDEX idx_entity_raw_trgm ON entities    USING gin (raw_text    gin_trgm_ops);

CREATE INDEX idx_fcd_tree ON focus_details(tree_id);
CREATE INDEX idx_fcr_required ON focus_requirements(required_focus);
"""

    let dialectFor (gameId: string) : Dialect =
        { Name = "postgres"
          TablesSql = dropSql + tablesSql gameId
          IndexesSql = Schema.indexesSql gameId
          SearchSql = searchSql
          ViewsSql = Schema.viewsSql
          SetupSql = [ "SET synchronous_commit TO off" ]
          FinalizeSql = [ "ANALYZE" ]
          AutoId = "DEFAULT"
          IgnoreConflict = fun sql -> sql + " ON CONFLICT DO NOTHING"
          NameParam = fun _ _ -> () // positional $1..$n; Npgsql binds by order
          PrepareCommand = fun _ -> () // server infers types; conn auto-prepares
          VerifyIntegrity = fun _ -> 0 // deferred FKs are validated at COMMIT
          RecordVersion =
            fun exec ->
                exec (
                    sprintf
                        "INSERT INTO meta VALUES ('schema_version', '%d') ON CONFLICT DO NOTHING"
                        Schema.UserVersion
                )
          OnDispose = fun () -> () }
